name: Sync Fork
on:
  schedule:
    - cron: '0 * * * *'  # 매 시간마다 자동 sync
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/lrycro/Cracker
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push
